"""cloud per-user tables

Revision ID: ff9123bfee52
Revises: ca4ae71d4189
Create Date: 2026-09-15 13:53:33.125097
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = 'ff9123bfee52'
down_revision: Union[str, Sequence[str], None] = 'ca4ae71d4189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_seniority',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('non_fit_reason', sa.String(), nullable=True),
    sa.Column('years_required', sa.Integer(), nullable=True),
    sa.Column('inferred', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('classified_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("level IN ('entry', 'mid', 'senior', 'senior_plus', 'staff', 'principal')", name='ck_job_seniority_level'),
    sa.CheckConstraint("non_fit_reason IN ('agency', 'contract', 'internship')", name='ck_job_seniority_non_fit_reason'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idp_subject', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('taxonomy_version_seen', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role IN ('user', 'admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('idp_subject')
    )
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('application_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("stage IN ('applied', 'recruiter_screen', 'interview', 'offer', 'rejected', 'withdrawn')", name='ck_application_events_stage'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_application_events_user_job', 'application_events', ['user_id', 'job_id'], unique=False)
    op.create_table('job_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('applied_resume_version', sa.String(), nullable=True),
    sa.Column('not_interested', sa.Boolean(), nullable=False),
    sa.Column('not_interested_note', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_job_tracking_user_job')
    )
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('storage_key', sa.String(), nullable=True),
    sa.Column('text_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('redacted_text', sa.Text(), nullable=True),
    sa.Column('skills_extracted', sa.JSON(), nullable=True),
    sa.Column('skills_confirmed', sa.JSON(), nullable=True),
    sa.Column('taxonomy_version', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'version', name='uq_resumes_user_version')
    )
    op.create_table('user_job_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('taxonomy_version', sa.String(), nullable=True),
    sa.Column('skill_score', sa.Integer(), nullable=True),
    sa.Column('skill_ratio', sa.Float(), nullable=True),
    sa.Column('skill_matched', sa.JSON(), nullable=True),
    sa.Column('skill_group_matched', sa.JSON(), nullable=True),
    sa.Column('skill_missing', sa.JSON(), nullable=True),
    sa.Column('seniority_fit', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_user_job_scores_user_job')
    )
    op.create_index('ix_user_job_scores_user_total', 'user_job_scores', ['user_id', 'total_score'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('seniority_target', sa.String(), nullable=False),
    sa.Column('target_roles', sa.JSON(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("seniority_target IN ('entry', 'mid', 'senior', 'senior_plus', 'staff', 'principal')", name='ck_user_profiles_seniority_target'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'version', name='uq_user_profiles_user_version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.drop_index('ix_user_job_scores_user_total', table_name='user_job_scores')
    op.drop_table('user_job_scores')
    op.drop_table('resumes')
    op.drop_table('job_tracking')
    op.drop_index('ix_application_events_user_job', table_name='application_events')
    op.drop_table('application_events')
    op.drop_table('api_tokens')
    op.drop_table('users')
    op.drop_table('job_seniority')
    # ### end Alembic commands ###
