"""baseline: schema of the local SQLite models

Revision ID: ca4ae71d4189
Revises: 
Create Date: 2026-09-15 13:46:02.182241
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = 'ca4ae71d4189'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('rendered', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('clicked', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('pages_planned', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_pages_recorded_at'), 'collection_pages', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_collection_pages_session_id'), 'collection_pages', ['session_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('homepage_url', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('research_report', sa.Text(), nullable=True),
    sa.Column('research_report_generated_at', sa.DateTime(), nullable=True),
    sa.Column('ats_provider', sa.String(), nullable=True),
    sa.Column('ats_slug', sa.String(), nullable=True),
    sa.Column('ats_checked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_table('extraction_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('strategies', sa.JSON(), nullable=True),
    sa.Column('failed_fields', sa.JSON(), nullable=True),
    sa.Column('snapshot_html', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_events_captured_at'), 'extraction_events', ['captured_at'], unique=False)
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('track', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('track', sa.String(), nullable=False),
    sa.Column('num_found', sa.Integer(), nullable=False),
    sa.Column('num_new', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('workplace_type', sa.String(), nullable=True),
    sa.Column('workplace_type_source', sa.String(), nullable=True),
    sa.Column('keyword_matched', sa.String(), nullable=False),
    sa.Column('track', sa.String(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('salary_text', sa.String(), nullable=True),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('posted_date', sa.String(), nullable=True),
    sa.Column('applicant_stats', sa.String(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('applied_resume_version', sa.String(), nullable=True),
    sa.Column('expired', sa.Boolean(), nullable=False),
    sa.Column('not_interested', sa.Boolean(), nullable=False),
    sa.Column('not_interested_note', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('repost_count', sa.Integer(), nullable=False),
    sa.Column('detail_fetched', sa.Boolean(), nullable=False),
    sa.Column('is_relevant', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of_job_id', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('posted_date_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of_job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=True)
    op.create_table('job_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'skill_name', name='uq_job_skill')
    )
    op.create_index(op.f('ix_job_skills_skill_name'), 'job_skills', ['skill_name'], unique=False)
    op.create_table('screening_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('skill_score', sa.Integer(), nullable=True),
    sa.Column('skill_ratio', sa.Float(), nullable=True),
    sa.Column('skill_matched', sa.JSON(), nullable=True),
    sa.Column('skill_group_matched', sa.JSON(), nullable=True),
    sa.Column('skill_missing', sa.JSON(), nullable=True),
    sa.Column('seniority_score', sa.Integer(), nullable=True),
    sa.Column('seniority_evidence', sa.Text(), nullable=True),
    sa.Column('seniority_years_required', sa.Integer(), nullable=True),
    sa.Column('seniority_inferred', sa.Boolean(), nullable=True),
    sa.Column('seniority_confidence', sa.String(), nullable=True),
    sa.Column('seniority_note', sa.Text(), nullable=True),
    sa.Column('expertise_score', sa.Integer(), nullable=True),
    sa.Column('expertise_evidence', sa.Text(), nullable=True),
    sa.Column('expertise_matched_domains', sa.JSON(), nullable=True),
    sa.Column('expertise_matched_capabilities', sa.JSON(), nullable=True),
    sa.Column('expertise_matched_weaknesses', sa.JSON(), nullable=True),
    sa.Column('expertise_confidence', sa.String(), nullable=True),
    sa.Column('expertise_note', sa.Text(), nullable=True),
    sa.Column('to_c_product_pm', sa.Boolean(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('screened_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('screening_results')
    op.drop_index(op.f('ix_job_skills_skill_name'), table_name='job_skills')
    op.drop_table('job_skills')
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('scrape_runs')
    op.drop_table('resume')
    op.drop_index(op.f('ix_extraction_events_captured_at'), table_name='extraction_events')
    op.drop_table('extraction_events')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_collection_pages_session_id'), table_name='collection_pages')
    op.drop_index(op.f('ix_collection_pages_recorded_at'), table_name='collection_pages')
    op.drop_table('collection_pages')
    op.drop_table('chat_messages')
    op.drop_table('career_goals')
    # ### end Alembic commands ###
