"""user_profiles.seniority_scores

Revision ID: 82e38a2e4655
Revises: ff9123bfee52
Create Date: 2026-09-16 14:18:05.959124
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '82e38a2e4655'
down_revision: Union[str, Sequence[str], None] = 'ff9123bfee52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('seniority_scores', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'seniority_scores')
    # ### end Alembic commands ###
